### PR TITLE
Add sendUserAgent to ConstructorOptions

### PR DESCRIPTION
**Pull request by alanzchen**

### CODE REVIEW

**Review by smusali — DISMISSED** [review]

**Review by mdeltito — DISMISSED** [review]

**Comment by mdeltito** [comment]
@logdnabot please test

**Comment by darinspivey** [comment]
@alanzchen This change looks fine, sorry about forgetting to update the type def file after the latest change!

Can we ask you to update your commit message, though?  We'd prefer a `type` in the title and also a brief description in the body: 

```
fix: Add `sendUserAgent` to `types.d.ts`

After the last feature commit, the new feature was not added into
the typescript definition file.
```

**Comment by alanzchen** [comment]
Just amended the commit messages

**Comment by darinspivey** [comment]
@logdnabot please test

**Review by darinspivey — APPROVED** [review]
Thanks for catching this!

**Review by smusali — APPROVED** [review]

**Pull request merged**
